- name: VPN WireGuard - stop service
  command: wg-quick down wg0
  ignore_errors: true

- name: VPN WireGuard - copy sysctl.conf with IP V4 setup
  copy:
    src: ./stuff/services/vpn-wireguard/sysctl.conf
    dest: /etc/sysctl.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"

- name: VPN Wireguard - reload sysctl
  command: sysctl -p

- name: VPN WireGuard - dependency iptables
  dnf:
    name: iptables
    state: installed

- name: VPN WireGuard - sleep 3
  pause:
    seconds: 3

- name: VPN WireGuard - copy server configuration
  template:
    src: ./stuff/services/vpn-wireguard/server/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-1

- name: VPN WireGuard - copy client configuration
  template:
    src: ./stuff/services/vpn-wireguard/client/wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-0

- name: VPN WireGuard - start service
  command: wg-quick up wg0

- name: VPN WireGuard - sleep 3
  pause:
    seconds: 3