- name: VPN WireGuard - copy Server private key
  copy:
    src: ./stuff/services/vpn-wireguard/keys/keyServerPrivate
    dest: /root/keyPrivate
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-1
  tags: "{{ tag_wireguard_keys_distribute }}"
- name: VPN WireGuard - copy Server public key
  copy:
    src: ./stuff/services/vpn-wireguard/keys/keyServerPublic
    dest: /root/keyPublic
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-1
  tags: "{{ tag_wireguard_keys_distribute }}"

- name: VPN WireGuard - copy Client private key
  copy:
    src: ./stuff/services/vpn-wireguard/keys/keyClientPrivate
    dest: /root/keyPrivate
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-0
  tags: "{{ tag_wireguard_keys_distribute }}"
- name: VPN WireGuard - copy Client public key
  copy:
    src: ./stuff/services/vpn-wireguard/keys/keyClientPublic
    dest: /root/keyPublic
    mode: u=rw,g=r,o=r #644
    owner: "{{ user_root }}"
    group: "{{ user_root }}"
  delegate_to: VM-0
  tags: "{{ tag_wireguard_keys_distribute }}"
