version: '3.8'

services:

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:2.7.12
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: userMarcin
      DOCKER_INFLUXDB_INIT_PASSWORD: passwordMarcin
      DOCKER_INFLUXDB_INIT_ORG: marcin-m-org
      DOCKER_INFLUXDB_INIT_BUCKET: marcin-bucket